import Head from "next/head";
import { Inter } from "@next/font/google";
import { gql } from "graphql-request";
import graphqlClient from "@/utils/graphql-client";
import PostCard from "@/components/post-card.component";
import Nav from "@/components/nav.component";
import FeaturedPostCard from "@/components/featured-post-card.component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const query = gql`
    query Assets {
      posts {
        excerpt
        title
      }
    }
  `;

  graphqlClient.request(query).then((data) => console.log(data));

  return (
    <>
      <Head>
        <title>Blog | Anindya Dey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <div className="px-6 py-4">
          <PostCard title="qwerty" excerpt="qwerty qwerty qwerty qwerty" />
        </div>
      </main>
    </>
  );
}
