import Head from 'next/head'
import { BlogPosts } from '../data/blog-posts'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>My Blogs</h1>
      </main>

      <div>
        {
          BlogPosts.map(blog => (
            <div key={blog.slug}>
              <div><Link href={`blogs/${blog.slug}`}><a>{blog.title}</a></Link></div>
              <div>{blog.createdOn}</div>
              <div>{blog.content}</div>
            </div>
          ))
        }
      </div>
    </div>
  )
}
