import Head from "next/head";
import { BlogPosts } from "../../data/blog-posts";

export default function BlogPage({ title, date, content }) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{title}</h1>
        <div>{date}</div>
        <div>{content}</div>
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
    console.log(JSON.stringify(context, null, ' '));
  const { params } = context;
  const blogPost = BlogPosts.find((post) => post.slug === params.slug);
  return {
    props: {
      ...blogPost,
    },
    revalidate: 10, // In seconds
  };
}

export async function getStaticPaths() {
  const paths = BlogPosts.map((post) => ({
    params: { slug: post.slug },
  }));
  return { paths, fallback: "blocking" };
}
